sudo: false
language: node_js
node_js:
- 8.11.4
script:
- npm install
- cd gem && ./bin/setup && bundle exec rake
deploy:
  provider: rubygems
  skip_cleanup: true
  api_key:
    secure: fjWHxa/lVOhSdH4VzHghTl7nKnj8wntYfOhGoEOdnBpwf498xligBF18NWMdJr0QdnqCbicXvTmR6R/iTVOAUKsV0T8cVVxhO4vk846NqJV0tjLVDFb8o5pHHsHNdd7zTyHWOVpEpZvw+5pcM1PHIIt1d2SBYodR1LOeFFs2fw0hCuBkru33hlBDKrf6rfdMEkSvG6sqmdIRxd1b9N4TgdCWaH5Gj9wZUF/hxQX1ieOFaAMxasEUlTvAZdh5PyiY7B6bLNKh4gwDX8m1Djwove1BVus4sNJ6iuev2YGzcEE+kuoQuPTphaTLnPzcSG4a3/ra4GTd9yPVvMF+FhBjywq+CpQqGDwKyieeDADQNB6zkHT9yZxzcw7l0Ds8olZp03RP+S/bpIE2Ms3cgWlKxwRyySLBgNqnBF+Lq64f77RC5tP3OLihpzWhQqOWn9Qg0NvGcSyRv8zaJgg52pZqyq69NvGKr/2zQsU1OhGio91nw612oayQBd5S7zsUqfuOphMVC5tvkKp54Dca/OfVqr830Q45ektB/ZrGoz+d+r6CNpLj+32ify1Fl/2+/JeNWOBXdHej8NX+X6Kj8JZp8UptZbU/g4RQrzHbIWnblN8LPiaLGdkJSTfqScnKOHiMQHEGos8yNtuOmhMPNkjzx6B6tuYlySA1/LMw5kG3de4=
  gem: mumuki-emojis
  on:
    tags: true
    repo: mumuki/mumuki-emojis
